# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DSC 10
description: DSC 10, Winter 2026 at UC San Diego
tagline: Principles of Data Science
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://dsc10.com' # the base hostname & protocol for your site, e.g. http://example.com
author: DSC 10 Instructors and Course Staff
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']

# reference these in the site using site.urls, e.g.:
#
# Check out our [Campuswire discussion forum]({{ site.urls.campuswire }}) for
# questions and announcements.
urls:
  campuswire: &campuswire 'https://campuswire.com/p/G54A20196'
  gradescope: &gradescope 'https://www.gradescope.com/courses/1189614'
  reference: &reference 'https://dsc-courses.github.io/bpd-reference/docs/documentation/intro'
  practice: &practice 'https://practice.dsc10.com/'
  cc: &cc 'http://cc.dsc10.com/'
  podcasts: &podcasts 'https://podcast.ucsd.edu/'
  syllabus_check: 'https://docs.google.com/forms/d/e/1FAIpQLSfcH_YKl2gY9lasAUSSkKDMiNrB82m4NZIEYdomYEoZoZl5Hw/viewform?usp=sharing&ouid=104866872711045167069'
  welcome_survey: 'https://docs.google.com/forms/d/e/1FAIpQLSc-Shhz9yTDWDri4MBfBlOsOyeZt_4VGxRBgkbKfVK75SclSQ/viewform?usp=sharing&ouid=104866872711045167069'

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: bluecsd
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  ðŸ™‹ Campuswire:
    - *campuswire
  ðŸ’¯ Gradescope:
    - *gradescope
  ðŸ“Œ Reference:
    - *reference
  ðŸ’ª Practice:
    - *practice
  âœ… CC:
    - *cc
  ðŸŽ¥ Podcasts:
    - *podcasts
footer_content:

# Collections for website data
collections:
  staffers:
  staffersnobio:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/staff-images/fa25'
  - scope:
      path: ''
      type: staffersnobio
    values:
      layout: staffer_no_bio
      subpath: '/assets/staff-images/fa25'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

# callouts
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important Announcement
    color: red
  note:
    title: Note
    color: yellow
  success:
    title: ''
    color: green
